services:
  users_app:
    build:
      context: users
      dockerfile: Dockerfile
    container_name: users_app
    command: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --reload"
    depends_on:
      - users_postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - dev_network

  users_postgres:
    image: postgres:latest
    container_name: users_postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/users/data/pgdata
    networks:
      - dev_network

  users_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: users_pgadmin
    depends_on:
      - users_postgres
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/users/pgadmin
    networks:
      - dev_network

volumes:
  pgdata:
  pgadmin:

networks:
  dev_network:
    driver: bridge
