FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./
COPY src ./src
COPY README.md ./

RUN pip install --upgrade pip poetry

RUN poetry config virtualenvs.create true \
    && poetry config virtualenvs.in-project true

RUN poetry install --no-interaction --no-ansi

ENV PATH="/app/.venv/bin:$PATH"

CMD ["pytest"]