[tool.poetry]
name = "fastapi-realtime-playground"
version = "0.1.0"
description = ""
authors = ["artyombn <balabashinan@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.128.0"
uvicorn = "^0.40.0"
pydantic = {extras = ["email"], version = "^2.12.5"}
sqlalchemy = "^2.0.45"
psycopg2-binary = "^2.9.11"
bcrypt = "^5.0.0"
python-jose = "^3.5.0"
python-dotenv = "^1.2.1"
gunicorn = "^25.0.1"
strawberry-graphql = {extras = ["debug-server"], version = "^0.291.2"}
secretstorage = "^3.5.0"
python-multipart = "^0.0.22"
alembic = "^1.18.3"
pydantic-settings = "^2.12.0"
httpx = "^0.28.1"
asyncpg = "^0.31.0"
pytest-asyncio = "^1.3.0"


[tool.poetry.group.dev.dependencies]
black = "^26.1.0"
pytest = "^9.0.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.appython --versioni"

[tool.pytest.ini_options]
python_files = "test_*.py *_test.py"
testpaths = ["src/tests"]

asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "session"

log_cli = false
addopts = "-v --maxfail=5"
#addopts = "-s -vv --tb=long --maxfail=5"

log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"


